language: php

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.5
        - php: 5.6
          env: COLLECT_COVERAGE=true
        - php: 7
        - php: hhvm
    allow_failures:
        - php: 7
        - php: hhvm

before_install:
    - composer self-update

install:
    - make setup

before_script:
    - mkdir -p "$HOME/.php-cs-fixer"

script:
    - make test
    - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run

after_script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "refactor" && "$COLLECT_COVERAGE" == "true" ]]; then bin/test-reporter; fi

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.php-cs-fixer

