language: php

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.5
        - php: 5.6
          env: COLLECT_COVERAGE=true
        - php: 7
    allow_failures:
        - php: 7

before_install:
    - nvm install 5.0.0
    - cd Api
    - composer self-update
    - cd ..

install:
    - cd Api
    - make composer
    - make setup
    - make database
    - cd ..
    - cd Blog
    - npm install
    - cd ..

before_script:
    - cd Api
    - mkdir -p "$HOME/.php-cs-fixer"
    - cd ..

script:
    - cd Api
    - make unit
    - make integration
    - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run
    - make validate
    - cd ..
    - cd Blog
    - grunt eslint
    - npm test
    - cd ..

after_script:
    - cd Api
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$COLLECT_COVERAGE" == "true" ]]; then bin/test-reporter; fi
    - cd ..

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.php-cs-fixer

addons:
    code_climate:
        repo_token: 1422e98c79dacf023e1a5710276ea033865b2884de913e957976f8da173d3ce5

