language: php

sudo: false

php:
    - 5.5
    - 5.6
    - hhvm

before_install:
    - composer self-update

install:
    - make setup

before_script:
    - mkdir -p "$HOME/.php-cs-fixer"

script:
    - make test
    - vendor/bin/php-cs-fixer fix --config-file=.php_cs --verbose --diff --dry-run

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.php-cs-fixer

