language: php

sudo: false

php:
    - 5.5
    - 5.6
    - hhvm

before_install:
    - composer self-update

install: 
    - composer install
    - cp .env.test .env

script: 
    - make test

cache:
    directories:
        - $HOME/.composer/cache

