articles_admin:
    resource: "@AdminBundle/Controller/ArticleController.php"
    type: annotation

article_show_admin:
    resource: "@AdminBundle/Controller/ArticleShowController.php"
    type: annotation

article_create_admin:
    resource: "@AdminBundle/Controller/ArticleCreateController.php"
    type: annotation

article_edit_admin:
    resource: "@AdminBundle/Controller/ArticleEditController.php"
    type: annotation

article_delete_admin:
    resource: "@AdminBundle/Controller/ArticleDeleteController.php"
    type: annotation
