services:
    aws_s3.client:
        class: Aws\S3\S3Client
        factory-class: Aws\S3\S3Client
        factory-method: 'factory'
        arguments:
            -
                key:    %amazon_s3_key%
                secret: %amazon_s3_secret%
                region: %amazon_s3_region%
