services:
    aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments: 
            -
                key: %amazon_s3_key%
                secret: %amazon_s3_secret%