services:
    article.repository:
        class: MyProject\Bundle\MainBundle\Entity\ArticleRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - MainBundle:Article

    tag.repository:
        class: MyProject\Bundle\MainBundle\Entity\TagRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - MainBundle:Tag
