imports:
    - { resource: config.yml }

framework:
    templating:
        assets_base_urls: ["http://s3.amazonaws.com/%amazon_s3_bucket_name%"]
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console


knp_gaufrette:
    filesystems:
        asset_fs:
            adapter: s3_assets

assetic:
    write_to: "s3://%amazon_s3_bucket_name%/assets"
