fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#AdminBundle
articles_admin:
    resource: "@AdminBundle/Resources/config/routing/article.yml"
    prefix: /admin/articles

tags:
    resource: "@AdminBundle/Controller/TagController.php"
    type: annotation

tag_create_admin:
    resource: "@AdminBundle/Controller/TagCreateController.php"
    type: annotation

tag_delete_admin:
    resource: "@AdminBundle/Controller/TagDeleteController.php"
    type: annotation

tag_edit_admin:
    resource: "@AdminBundle/Controller/TagEditController.php"
    type: annotation

tag_show_admin:
    resource: "@AdminBundle/Controller/TagShowController.php"
    type: annotation

# MainBundle
myproject:
    resource: "@MainBundle/Controller/MainController.php"
    type: annotation

login:
    resource: "@MainBundle/Controller/LoginController.php"
    type: annotation
