fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

# Disallow registering
# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


myproject:
    resource: "@MainBundle/Controller/MainController.php"
    type: annotation

articles:
    resource: "@MainBundle/Resources/config/routing/article.yml"
    prefix: /articles

login:
    resource: "@MainBundle/Controller/LoginController.php"
    type: annotation
