<?php

namespace MyProject\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findArticles($offset, $limit)
    {
        return $this->createQueryBuilder('MainBundle:Article')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->orderBy('MainBundle:Article.createdAt', 'DESC')
            ->getQuery()
            ->getArrayResult()
        ;
    }
}
