<?php

namespace MyProject\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findAllNames()
    {
        return $this->createQueryBuilder('t')
            ->select(
                array('t.name')
            )
            ->getQuery()
            ->execute()
        ;
    }

    public function findOneByName($name)
    {
        $qb = $this->createQueryBuilder('t');

        $eq = $qb->expr()->eq(
            't.name',
            sprintf(
                "'%s'",
                $name
            )
        );

        return $qb->where($eq)
            ->getQuery()
            ->getSingleResult()
        ;
    }
}
